# f = open("newcar.py","r")
# # print(f.read())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# f.close()

# f = open("C:\Users\ACER\OneDrive\Desktop\Notes of python\note1.txt","r")
# print(f.read())
# f.close()

# f = open("newcar.py","a")
# f.write("#world")
# f.close()
# f=open("newcar.py","r")
# print(f.read())

# import os
# os.remove("rrr.py")
